---
- name: Symlink service logs folder
  file:
    src: '/var/log/service/{{ nimbus_eth1_service_name }}'
    dest: '{{ nimbus_eth1_logs_link }}'
    state: 'link'
    force: true

- name: Create systemd Unit file
  template:
    src: 'nimbus-eth1-benchmark.service.j2'
    dest: '/etc/systemd/system/{{ nimbus_eth1_service_name }}.service'
    mode: 0644

- name: Create Service Scripts
  template:
    src: "{{ item }}"
    dest: "{{ nimbus_eth1_service_scripts_base }}/{{ item }}"
    owner: '{{ nimbus_eth1_service_user }}'
    group: '{{ nimbus_eth1_service_group }}'
    mode: 0775
  loop:
    - 'run-benchmark.sh'
    - 'results-processing.sh'
    - 'repo-management.sh'
    - 'build-and-compile.sh'
    - 'benchmark-execution.sh'

- name: Reload systemctl
  command: systemctl daemon-reload
