---
- name: Symlink service logs folder
  file:
    src: '/var/log/service/{{ nimbus_eth1_service_name }}'
    dest: '{{ nimbus_eth1_logs_link }}'
    state: 'link'
    force: true

- name: Create systemd Unit file
  template:
    src: 'nimbus-eth1-{{ nimbus_eth1_benchmark_type }}-benchmark.service.j2'
    dest: '/etc/systemd/system/{{ nimbus_eth1_service_name }}.service'
    mode: 0644

- name: Create build script
  template:
    src: 'build.sh.j2'
    dest: '{{ nimbus_eth1_build_script }}'
    owner: '{{ nimbus_eth1_service_user }}'
    group: '{{ nimbus_eth1_service_group }}'
    mode: 0775

- name: Create benchmarking repo fetching script
  template:
    src: 'fetch-benchmarks.sh.j2'
    dest: '{{ nimbus_eth1_benchmark_gen_script }}'
    owner: '{{ nimbus_eth1_service_user }}'
    group: '{{ nimbus_eth1_service_group }}'
    mode: 0775

- name: Create metrics github publish script
  template:
    src: 'publish-metrics-github.sh.j2'
    dest: '{{ nimbus_eth1_publish_script }}'
    owner: '{{ nimbus_eth1_service_user }}'
    group: '{{ nimbus_eth1_service_group }}'
    mode: 0775

- name: Create Database generation and cleanup script
  template:
    src: 'database-generation-and-cleanup.sh.j2'
    dest: '{{ nimbus_eth1_db_gen_script }}'
    owner: '{{ nimbus_eth1_service_user }}'
    group: '{{ nimbus_eth1_service_group }}'
    mode: 0775
  when: nimbus_eth1_benchmark_type == 'short'

- name: Create log files
  file:
    path: "{{ item }}"
    state: touch
    owner: '{{ nimbus_eth1_service_user }}'
    group: '{{ nimbus_eth1_service_group }}'
    mode: '0644'
  loop:
    - '{{ nimbus_eth1_benchmark_log_output_file_path }}'
    - '{{ nimbus_eth1_benchmark_log_error_file_path }}'

- name: Reload systemctl
  command: systemctl daemon-reload
