---
- name: Symlink service logs folder
  file:
    src: '/var/log/service/{{ nimbus_eth1_service_name }}'
    dest: '{{ nimbus_eth1_logs_link }}'
    state: 'link'
    force: true

- name: Create systemd Unit file
  template:
    src: 'nimbus-eth1-benchmark.service.j2'
    dest: '/etc/systemd/system/{{ nimbus_eth1_service_name }}.service'
    mode: 0644

- name: Create benchmark environment file
  template:
    src: 'benchmark.env.j2'
    dest: '{{ nimbus_eth1_service_scripts_base }}/benchmark.env'
    owner: '{{ nimbus_eth1_service_user }}'
    group: '{{ nimbus_eth1_service_group }}'
    mode: 0644

- name: Create Service Scripts
  copy:
    src: "{{ item | basename }}"
    dest: "{{ nimbus_eth1_service_scripts_base }}/{{ item | basename }}"
    owner: '{{ nimbus_eth1_service_user }}'
    group: '{{ nimbus_eth1_service_group }}'
    mode: 0775
  with_fileglob:
    - "../files/*.sh"

- name: Reload systemctl
  command: systemctl daemon-reload
