#!/usr/bin/env bash
# vim: ft=sh
set -e

function buildBinaries() {

  cd "${NIMBUS_ETH1_REPO}"
  local COMMIT=$(git rev-parse --short=8 HEAD)

  if [[ -f "build/nimbus_execution_client_${COMMIT}" ]]; then
    echo ">>> Binaries already exist for commit ${COMMIT}, no need to build a new nimbus binary!"
    return
  fi

  echo ">>> Building binaries for commit ${COMMIT}..."

  make -j16 update
  make -j16 nimbus_execution_client \
    LOG_LEVEL="DEBUG" NIMFLAGS="-d:chronicles_colors=none -d:disableMarchNative" ROCKSDB_CI_CACHE="${NIMBUS_ETH1_REPO}/build"

  echo ">>> renaming binaries to match commit they were built from"
  mv "build/nimbus_execution_client" "build/nimbus_execution_client_${COMMIT}"

  echo ">>> creating a symbolic link to the latest version"
  ln -frs build/nimbus_execution_client_${COMMIT} build/nimbus_execution_client

  echo ">>> deleting copies that are older than N days"
  find build -mtime +3 -exec rm '{}' \+

}

function copyTemplateDatabase() {
  # this path is generated by nimbus, however in case of short benchmark this path may get cleaned up
  mkdir -p "${NIMBUS_ETH1_DB_DIR}"

  echo ">>> Copying template db into nimbus data directory"
  cp -r "${NIMBUS_ETH1_TEMPLATE_DB}/." "$NIMBUS_ETH1_DB_DIR/"
  echo ">>> Template db copied"

  echo ">>> making nimbus the owner of the copied files"
  chown -R "$(id -u -n):$(id -g -n)" "${NIMBUS_ETH1_DB_DIR}"
}
